import { Roboto } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Navbar from "./components/navbar";

const roboto = Roboto({
  weight: "300",
  subsets: ["latin"],
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body className={roboto.className}>{children}</body>
      </html>
    </>
  );
}
